# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Joshuami
tagline:          'A place for Josh Mitchell to write'
description:      'Josh Mitchell is a technology leader, architect of enterprise solutions, and builder of high performing teams.'
url:              http://joshuami.com
baseurl:          /

author:
  name:           'Josh Mitchell'
  url:            https://twitter.com/joshua_io

# Custom vars
github:
  repo:           https://joshuami.github.io

menu:
  Home: '/'
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
