ai_simple_provider_installer.settings:
  type: config_object
  label: 'AI Simple Provider Installer settings'
  mapping:
    redirect_route:
      type: string
      label: 'The route to redirect to after the form is submitted'
    content_removal:
      type: sequence
      label: 'Content removal entities'
      sequence:
        type: string
        label: 'Entity type and uuid'
