<?php

/**
 * @file
 * Highlight.js Input Filter module functions.
 */

/**
 * Implements hook_library_info_build().
 *
 * Used to dynamically import the CSS file based on this module's configuration.
 */
function highlightjs_input_filter_library_info_build() {
  $libraries = [];
  $theme = \Drupal::config('highlightjs_input_filter.settings')->get('theme');
  $libraries['highlightjs_input_filter.styles'] = [
    'css' => [
      'theme' => [
        'https://unpkg.com/@highlightjs/cdn-assets@11.9.0/styles/' . $theme . '.min.css' => [
          'type' => 'external',
          'minified' => TRUE,
        ],
      ],
    ],
  ];

  return $libraries;
}
