_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: 6c0d20e1-fd79-48de-9149-0e141ace4358
name: Joshuami
mail: no-reply@joshuami.com
slogan: 'Weblog of Josh Mitchell—a technology leader, architect of enterprise solutions, and builder of high performing teams.'
page:
  403: /user/login
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
