highlightjs_input_filter.settings:
  type: config_object
  label: 'highlightjs Input Filter settings'
  mapping:
    enable_copy_button:
      type: boolean
      label: 'Enable copy button'
    theme:
      type: string
      label: 'Theme'
