name: AI Support
type: Drupal CMS
description: 'Adds possibility to have an admin chatbot with agents and helps with generating image alt text.'
install:
  - key
  - block
  - taxonomy
  - ai
  - ai_provider_openai
  - ai_provider_anthropic
  - ai_image_alt_text
  - ai_assistant_api
  - ai_chatbot
  - ai_agents
  - menu_link_content
recipes:
  - core/recipes/content_editor_role
config:
  import:
    ai_image_alt_text: '*'
  actions:
    ai_agents.settings:
      simpleConfigUpdate:
        agent_settings:
          field_type_agent:
            usage_instructions: >
              If they ask you to change an edit form, assume they want you to change the fields on a content type if they are visiting a node form.

              If they ask to create an Image Field, assume they want an Media Field with the image bundle, unless they tell you not to create a media field. Specifically ask for an Entity Reference Field with Entity Type media and the bundle image. Always set the form widget to Media Library if its available and the view mode to Rendered Entity.
            permissions:
              authenticated: 0
              content_editor: 0
              administrator: 0
            plugin_settings: {  }
    block.block.ai_chatbot:
      placeBlockInAdminTheme:
        region:
          gin: content
          claro: content
        default_region: content
        plugin: ai_deepchat_block
        settings:
          id: ai_deepchat_block
          label: 'Drupal Agent Chatbot'
          label_display: '0'
          provider: ai_chatbot
          ai_assistant: drupal_agent_assistant
          bot_name: 'Drupal Agent'
          stream: 0
          default_avatar: /core/misc/druplicon.png
          first_message: 'Hello! How can I assist you today?'
          show_structured_results: 1
    user.role.content_editor:
      grantPermission: 'generate ai alt tags'
