name: Accessibility tools
type: Drupal CMS
description: Installs and configures tools to help authors make their content accessible.
recipes:
  - drupal_cms_page
install:
  - editoria11y
config:
  strict: false
  import:
    editoria11y: '*'
  actions:
    editoria11y.settings:
      simpleConfigUpdate:
        # Map tiles contain no alt text.
        # Skipping the map pane to limit reports
        # where the fix is outwith editors control.
        ignore_elements: '.leaflet-map-pane *'
