name: Forms
type: Drupal CMS
description: Provides a simple contact form, and tools for building more complex forms.
recipes:
  - drupal_cms_anti_spam
install:
  - captcha
  - editor
  - filter
  - menu_link_content
  - shortcut
  - views
  - webform
  - webform_ui
input:
  captcha:
    data_type: boolean
    description: 'Whether to show a CAPTCHA on the contact form.'
    prompt:
      method: confirm
      arguments:
        question: 'Do you want to show a CAPTCHA on the contact form?'
        default: false
    default:
      source: value
      value: false
config:
  # If Webform's config already exists, we don't really care what it looks like.
  strict: false
  import:
    shortcut:
      - shortcut.set.default
    system:
      - system.menu.main
    webform:
      - system.action.webform_archive_action
      - system.action.webform_close_action
      - system.action.webform_delete_action
      - system.action.webform_open_action
      - system.action.webform_submission_delete_action
      - system.action.webform_submission_make_lock_action
      - system.action.webform_submission_make_sticky_action
      - system.action.webform_submission_make_unlock_action
      - system.action.webform_submission_make_unsticky_action
      - system.action.webform_unarchive_action
      - editor.editor.webform_default
      - filter.format.webform_default
      - views.view.webform_submissions
  actions:
    # We provide a CAPTCHA but disable it by default, since CAPTCHAs are obstacles
    # by design.
    captcha.captcha_point.webform_submission_contact_form_add_form:
      setStatus: ${captcha}
    webform.settings:
      simpleConfigUpdate:
        ui.promotions_disabled: true
